// Method 4 Atomic Operation Contract Addresses
// Auto-generated by deployMethod4Complete.ts

export interface ContractAddresses {
  taskEscrow: string;
  echoToken: string;
  register: string;
  universalReward: string;
}

// Chain configuration
export const DEFAULT_CHAIN_ID = 7001; // ZetaChain Athens Testnet
export const SUPPORTED_CHAIN_IDS = [31337, 7001]; // Local Hardhat + ZetaChain Athens

export function getContractAddresses(chainId: number): ContractAddresses {
  if (chainId === 31337) {
    // Local Hardhat Network - Method 4 (Updated after double charging fix)
    return {
      taskEscrow: '0x0165878A594ca255338adfa4d48449f69242Eb8F',
      echoToken: '0x5FbDB2315678afecb367f032d93F642f64180aa3',
      register: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512',
      universalReward: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'
    };
  }
  
  if (chainId === 7001) {
    // ZetaChain Athens Testnet - Method 4 (Complete system redeploy - Fresh deployment)
    return {
      taskEscrow: '0x69B200141cF9553C2D17834AF149248A035Dc52B',
      echoToken: '0x937f10827b9Ccd99033eFEeBA26d519992F4B1AF',
      register: '0x1F8dD0d186fd77F4F1B98067B031437e8025162C',
      universalReward: '0x8fA4C878b22279C5f602c4e9B6EC85BD23EFC6b3'
    };
  }
  
  throw new Error(`Unsupported chain ID: ${chainId}`);
}

// Legacy function for backward compatibility
export function getAtomicOperationAddresses(chainId: number) {
  const addresses = getContractAddresses(chainId);
  return {
    taskRewardCoordinator: addresses.taskEscrow, // TaskEscrow now handles atomic operations
    universalReward: addresses.universalReward
  };
}
